# Generated by Django 5.0.2 on 2024-02-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='size',
        ),
        migrations.AddField(
            model_name='planet',
            name='max_distance_from_star',
            field=models.FloatField(default=1000, help_text='In million kilometers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='min_distance_from_star',
            field=models.FloatField(default=1000, help_text='In million kilometers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='orbital_period',
            field=models.IntegerField(default=100, help_text='In Earth days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='radius',
            field=models.IntegerField(default=1000, help_text='In kilometers'),
            preserve_default=False,
        ),
    ]
